import type { ComponentType, SVGProps } from 'react'
import {
  FolderKanban,
  Folder,
  FolderOpen,
  LayoutDashboard,
  Layers,
  Box,
  Package,
  Boxes,
  Archive,
  Bookmark,
  Flag,
  Target,
  Compass,
  Map,
  Rocket,
  Sparkles,
  Star,
  Zap,
  Lightbulb,
  Puzzle,
  Shapes,
  Hexagon,
  CircleDot,
  Kanban,
  ListChecks,
  ClipboardList,
  ClipboardCheck,
  Calendar,
  CalendarDays,
  Clock,
  Timer,
  Hourglass,
  Bell,
  Megaphone,
  Trophy,
  Award,
  Medal,
  Crown,
  Gem,
  Gift,
  Flame,
  Briefcase,
  Handshake,
  Users,
  User,
  UserPlus,
  Contact,
  IdCard,
  BadgeCheck,
  Building,
  Building2,
  Store,
  Factory,
  Warehouse,
  Landmark,
  School,
  Home,
  Coins,
  Banknote,
  CreditCard,
  Wallet,
  PiggyBank,
  Receipt,
  Percent,
  Calculator,
  Scale,
  ShoppingCart,
  ShoppingBag,
  Tag,
  Tags,
  Ticket,
  QrCode,
  Barcode,
  ChartBar,
  ChartLine,
  ChartPie,
  TrendingUp,
  Cpu,
  Server,
  Database,
  HardDrive,
  Cloud,
  CloudUpload,
  Code,
  Terminal,
  Bug,
  GitBranch,
  GitMerge,
  GitPullRequest,
  Monitor,
  Laptop,
  Smartphone,
  Tablet,
  Tv,
  Radio,
  Headphones,
  Mic,
  Camera,
  Video,
  Image,
  Wifi,
  Bluetooth,
  Signal,
  Antenna,
  Battery,
  Plug,
  Power,
  Bot,
  Brain,
  Magnet,
  Gauge,
  Settings,
  Wrench,
  Hammer,
  Cog,
  Shield,
  ShieldCheck,
  Lock,
  Key,
  Fingerprint,
  Eye,
  Scan,
  Search,
  Filter,
  Palette,
  Paintbrush,
  PenTool,
  Pencil,
  Brush,
  Scissors,
  Ruler,
  Sticker,
  Type,
  Book,
  BookOpen,
  Library,
  Newspaper,
  FileText,
  Files,
  Notebook,
  GraduationCap,
  Mail,
  Send,
  MessageCircle,
  MessageSquare,
  Phone,
  AtSign,
  Rss,
  Link,
  Share2,
  Heart,
  Sun,
  Moon,
  Umbrella,
  Anchor,
  Feather,
  Leaf,
  Flower,
  TreePine,
  Mountain,
  Globe,
  Plane,
  Car,
  Truck,
  Ship,
  TrainFront,
  Bike,
  Bus,
  Utensils,
  Coffee,
  Pizza,
  Wine,
  Dumbbell,
  Footprints,
  Activity,
  HeartPulse,
  Stethoscope,
  Pill,
  Syringe,
  Microscope,
  FlaskConical,
  Atom,
  Dna,
  TestTube,
  Orbit,
  Telescope,
  Satellite,
} from 'lucide-react'

/**
 * Project icon library (Round P R5). A project's `icon` is either a legacy
 * emoji (6 stock glyphs from Round C, kept as-is) or `lucide:<name>` from
 * this curated set, drawn white on a colour tile (`color`, #RRGGBB). A
 * project shows EITHER its icon tile OR an uploaded image (`logo_key`):
 * choosing an icon clears the image on the server, uploading an image hides
 * the icon until "Remove image" — the icon + colour stay stored so they come
 * straight back.
 *
 * Only the curated names are imported (tree-shakable named imports — never
 * the `icons` catalogue, which is ~1,700 glyphs). The API (both the REST
 * DTOs and the service, which the offline-sync door calls directly) accepts
 * `lucide:[a-z0-9-]{1,24}` — any letter-case of the `lucide:` prefix must be
 * a well-formed lower-case name — or a 1–16 character emoji without
 * whitespace/control characters; `color` must be #RRGGBB. A curated-set miss
 * renders the default tile so an older client never breaks a newer server.
 */

export type LucideGlyph = ComponentType<
  SVGProps<SVGSVGElement> & { size?: number | string; strokeWidth?: number | string; absoluteStrokeWidth?: boolean }
>

export const PROJECT_ICON_PREFIX = 'lucide:'
export const DEFAULT_PROJECT_ICON = 'lucide:folder-kanban'

/** Curated, grouped, in display order. Values are bare lucide names (no prefix). */
export const PROJECT_ICON_GROUPS: ReadonlyArray<{ group: string; icons: readonly string[] }> = [
  { group: 'Work', icons: ['folder-kanban', 'folder', 'folder-open', 'layout-dashboard', 'layers', 'box', 'package', 'boxes', 'archive', 'bookmark', 'flag', 'target', 'compass', 'map', 'rocket', 'sparkles', 'star', 'zap', 'lightbulb', 'puzzle', 'shapes', 'hexagon', 'circle-dot', 'kanban', 'list-checks', 'clipboard-list', 'clipboard-check', 'calendar', 'calendar-days', 'clock', 'timer', 'hourglass', 'bell', 'megaphone', 'trophy', 'award', 'medal', 'crown', 'gem', 'gift', 'flame'] },
  { group: 'Business', icons: ['briefcase', 'handshake', 'users', 'user', 'user-plus', 'contact', 'id-card', 'badge-check', 'building', 'building-2', 'store', 'factory', 'warehouse', 'landmark', 'school', 'home', 'coins', 'banknote', 'credit-card', 'wallet', 'piggy-bank', 'receipt', 'percent', 'calculator', 'scale', 'shopping-cart', 'shopping-bag', 'tag', 'tags', 'ticket', 'qr-code', 'barcode', 'chart-bar', 'chart-line', 'chart-pie', 'trending-up'] },
  { group: 'Tech', icons: ['cpu', 'server', 'database', 'hard-drive', 'cloud', 'cloud-upload', 'code', 'terminal', 'bug', 'git-branch', 'git-merge', 'git-pull-request', 'monitor', 'laptop', 'smartphone', 'tablet', 'tv', 'radio', 'headphones', 'mic', 'camera', 'video', 'image', 'wifi', 'bluetooth', 'signal', 'antenna', 'battery', 'plug', 'power', 'bot', 'brain', 'magnet', 'gauge', 'settings', 'wrench', 'hammer', 'cog', 'shield', 'shield-check', 'lock', 'key', 'fingerprint', 'eye', 'scan', 'search', 'filter'] },
  { group: 'Design', icons: ['palette', 'paintbrush', 'pen-tool', 'pencil', 'brush', 'scissors', 'ruler', 'sticker', 'type', 'book', 'book-open', 'library', 'newspaper', 'file-text', 'files', 'notebook', 'graduation-cap', 'mail', 'send', 'message-circle', 'message-square', 'phone', 'at-sign', 'rss', 'link', 'share-2'] },
  { group: 'Life', icons: ['heart', 'sun', 'moon', 'umbrella', 'anchor', 'feather', 'leaf', 'flower', 'tree-pine', 'mountain', 'globe', 'plane', 'car', 'truck', 'ship', 'train-front', 'bike', 'bus', 'utensils', 'coffee', 'pizza', 'wine', 'dumbbell', 'footprints', 'activity', 'heart-pulse', 'stethoscope', 'pill', 'syringe', 'microscope', 'flask-conical', 'atom', 'dna', 'test-tube', 'orbit', 'telescope', 'satellite'] },
]

const GLYPHS: Record<string, LucideGlyph> = {
  'folder-kanban': FolderKanban as LucideGlyph,
  'folder': Folder as LucideGlyph,
  'folder-open': FolderOpen as LucideGlyph,
  'layout-dashboard': LayoutDashboard as LucideGlyph,
  'layers': Layers as LucideGlyph,
  'box': Box as LucideGlyph,
  'package': Package as LucideGlyph,
  'boxes': Boxes as LucideGlyph,
  'archive': Archive as LucideGlyph,
  'bookmark': Bookmark as LucideGlyph,
  'flag': Flag as LucideGlyph,
  'target': Target as LucideGlyph,
  'compass': Compass as LucideGlyph,
  'map': Map as LucideGlyph,
  'rocket': Rocket as LucideGlyph,
  'sparkles': Sparkles as LucideGlyph,
  'star': Star as LucideGlyph,
  'zap': Zap as LucideGlyph,
  'lightbulb': Lightbulb as LucideGlyph,
  'puzzle': Puzzle as LucideGlyph,
  'shapes': Shapes as LucideGlyph,
  'hexagon': Hexagon as LucideGlyph,
  'circle-dot': CircleDot as LucideGlyph,
  'kanban': Kanban as LucideGlyph,
  'list-checks': ListChecks as LucideGlyph,
  'clipboard-list': ClipboardList as LucideGlyph,
  'clipboard-check': ClipboardCheck as LucideGlyph,
  'calendar': Calendar as LucideGlyph,
  'calendar-days': CalendarDays as LucideGlyph,
  'clock': Clock as LucideGlyph,
  'timer': Timer as LucideGlyph,
  'hourglass': Hourglass as LucideGlyph,
  'bell': Bell as LucideGlyph,
  'megaphone': Megaphone as LucideGlyph,
  'trophy': Trophy as LucideGlyph,
  'award': Award as LucideGlyph,
  'medal': Medal as LucideGlyph,
  'crown': Crown as LucideGlyph,
  'gem': Gem as LucideGlyph,
  'gift': Gift as LucideGlyph,
  'flame': Flame as LucideGlyph,
  'briefcase': Briefcase as LucideGlyph,
  'handshake': Handshake as LucideGlyph,
  'users': Users as LucideGlyph,
  'user': User as LucideGlyph,
  'user-plus': UserPlus as LucideGlyph,
  'contact': Contact as LucideGlyph,
  'id-card': IdCard as LucideGlyph,
  'badge-check': BadgeCheck as LucideGlyph,
  'building': Building as LucideGlyph,
  'building-2': Building2 as LucideGlyph,
  'store': Store as LucideGlyph,
  'factory': Factory as LucideGlyph,
  'warehouse': Warehouse as LucideGlyph,
  'landmark': Landmark as LucideGlyph,
  'school': School as LucideGlyph,
  'home': Home as LucideGlyph,
  'coins': Coins as LucideGlyph,
  'banknote': Banknote as LucideGlyph,
  'credit-card': CreditCard as LucideGlyph,
  'wallet': Wallet as LucideGlyph,
  'piggy-bank': PiggyBank as LucideGlyph,
  'receipt': Receipt as LucideGlyph,
  'percent': Percent as LucideGlyph,
  'calculator': Calculator as LucideGlyph,
  'scale': Scale as LucideGlyph,
  'shopping-cart': ShoppingCart as LucideGlyph,
  'shopping-bag': ShoppingBag as LucideGlyph,
  'tag': Tag as LucideGlyph,
  'tags': Tags as LucideGlyph,
  'ticket': Ticket as LucideGlyph,
  'qr-code': QrCode as LucideGlyph,
  'barcode': Barcode as LucideGlyph,
  'chart-bar': ChartBar as LucideGlyph,
  'chart-line': ChartLine as LucideGlyph,
  'chart-pie': ChartPie as LucideGlyph,
  'trending-up': TrendingUp as LucideGlyph,
  'cpu': Cpu as LucideGlyph,
  'server': Server as LucideGlyph,
  'database': Database as LucideGlyph,
  'hard-drive': HardDrive as LucideGlyph,
  'cloud': Cloud as LucideGlyph,
  'cloud-upload': CloudUpload as LucideGlyph,
  'code': Code as LucideGlyph,
  'terminal': Terminal as LucideGlyph,
  'bug': Bug as LucideGlyph,
  'git-branch': GitBranch as LucideGlyph,
  'git-merge': GitMerge as LucideGlyph,
  'git-pull-request': GitPullRequest as LucideGlyph,
  'monitor': Monitor as LucideGlyph,
  'laptop': Laptop as LucideGlyph,
  'smartphone': Smartphone as LucideGlyph,
  'tablet': Tablet as LucideGlyph,
  'tv': Tv as LucideGlyph,
  'radio': Radio as LucideGlyph,
  'headphones': Headphones as LucideGlyph,
  'mic': Mic as LucideGlyph,
  'camera': Camera as LucideGlyph,
  'video': Video as LucideGlyph,
  'image': Image as LucideGlyph,
  'wifi': Wifi as LucideGlyph,
  'bluetooth': Bluetooth as LucideGlyph,
  'signal': Signal as LucideGlyph,
  'antenna': Antenna as LucideGlyph,
  'battery': Battery as LucideGlyph,
  'plug': Plug as LucideGlyph,
  'power': Power as LucideGlyph,
  'bot': Bot as LucideGlyph,
  'brain': Brain as LucideGlyph,
  'magnet': Magnet as LucideGlyph,
  'gauge': Gauge as LucideGlyph,
  'settings': Settings as LucideGlyph,
  'wrench': Wrench as LucideGlyph,
  'hammer': Hammer as LucideGlyph,
  'cog': Cog as LucideGlyph,
  'shield': Shield as LucideGlyph,
  'shield-check': ShieldCheck as LucideGlyph,
  'lock': Lock as LucideGlyph,
  'key': Key as LucideGlyph,
  'fingerprint': Fingerprint as LucideGlyph,
  'eye': Eye as LucideGlyph,
  'scan': Scan as LucideGlyph,
  'search': Search as LucideGlyph,
  'filter': Filter as LucideGlyph,
  'palette': Palette as LucideGlyph,
  'paintbrush': Paintbrush as LucideGlyph,
  'pen-tool': PenTool as LucideGlyph,
  'pencil': Pencil as LucideGlyph,
  'brush': Brush as LucideGlyph,
  'scissors': Scissors as LucideGlyph,
  'ruler': Ruler as LucideGlyph,
  'sticker': Sticker as LucideGlyph,
  'type': Type as LucideGlyph,
  'book': Book as LucideGlyph,
  'book-open': BookOpen as LucideGlyph,
  'library': Library as LucideGlyph,
  'newspaper': Newspaper as LucideGlyph,
  'file-text': FileText as LucideGlyph,
  'files': Files as LucideGlyph,
  'notebook': Notebook as LucideGlyph,
  'graduation-cap': GraduationCap as LucideGlyph,
  'mail': Mail as LucideGlyph,
  'send': Send as LucideGlyph,
  'message-circle': MessageCircle as LucideGlyph,
  'message-square': MessageSquare as LucideGlyph,
  'phone': Phone as LucideGlyph,
  'at-sign': AtSign as LucideGlyph,
  'rss': Rss as LucideGlyph,
  'link': Link as LucideGlyph,
  'share-2': Share2 as LucideGlyph,
  'heart': Heart as LucideGlyph,
  'sun': Sun as LucideGlyph,
  'moon': Moon as LucideGlyph,
  'umbrella': Umbrella as LucideGlyph,
  'anchor': Anchor as LucideGlyph,
  'feather': Feather as LucideGlyph,
  'leaf': Leaf as LucideGlyph,
  'flower': Flower as LucideGlyph,
  'tree-pine': TreePine as LucideGlyph,
  'mountain': Mountain as LucideGlyph,
  'globe': Globe as LucideGlyph,
  'plane': Plane as LucideGlyph,
  'car': Car as LucideGlyph,
  'truck': Truck as LucideGlyph,
  'ship': Ship as LucideGlyph,
  'train-front': TrainFront as LucideGlyph,
  'bike': Bike as LucideGlyph,
  'bus': Bus as LucideGlyph,
  'utensils': Utensils as LucideGlyph,
  'coffee': Coffee as LucideGlyph,
  'pizza': Pizza as LucideGlyph,
  'wine': Wine as LucideGlyph,
  'dumbbell': Dumbbell as LucideGlyph,
  'footprints': Footprints as LucideGlyph,
  'activity': Activity as LucideGlyph,
  'heart-pulse': HeartPulse as LucideGlyph,
  'stethoscope': Stethoscope as LucideGlyph,
  'pill': Pill as LucideGlyph,
  'syringe': Syringe as LucideGlyph,
  'microscope': Microscope as LucideGlyph,
  'flask-conical': FlaskConical as LucideGlyph,
  'atom': Atom as LucideGlyph,
  'dna': Dna as LucideGlyph,
  'test-tube': TestTube as LucideGlyph,
  'orbit': Orbit as LucideGlyph,
  'telescope': Telescope as LucideGlyph,
  'satellite': Satellite as LucideGlyph,
}

/** Twelve swatches — brand blue first; each tile is white on this colour. */
export const PROJECT_COLORS: ReadonlyArray<{ value: string; label: string }> = [
  { value: '#2563EB', label: 'Blue' },
  { value: '#0891B2', label: 'Teal' },
  { value: '#059669', label: 'Green' },
  { value: '#65A30D', label: 'Lime' },
  { value: '#CA8A04', label: 'Amber' },
  { value: '#EA580C', label: 'Orange' },
  { value: '#DC2626', label: 'Red' },
  { value: '#DB2777', label: 'Pink' },
  { value: '#9333EA', label: 'Purple' },
  { value: '#4F46E5', label: 'Indigo' },
  { value: '#475569', label: 'Slate' },
  { value: '#1F2937', label: 'Charcoal' },
]

export const DEFAULT_PROJECT_COLOR = PROJECT_COLORS[0].value

export const HEX_COLOR_RE = /^#[0-9a-fA-F]{6}$/

/** `lucide:<name>` with a name in the curated set. */
export function isLucideIcon(value: string | null | undefined): value is `lucide:${string}` {
  return typeof value === 'string' && value.startsWith(PROJECT_ICON_PREFIX) && value.slice(PROJECT_ICON_PREFIX.length) in GLYPHS
}

/** Any `lucide:` value, curated or not (an unknown name draws the default glyph). */
export function looksLikeLucideIcon(value: string | null | undefined): boolean {
  return typeof value === 'string' && /^lucide:[a-z0-9-]{1,24}$/.test(value)
}

/** The React component for a `lucide:<name>` value; the default glyph for unknown names; null for emoji / empty. */
export function lucideComponent(value: string | null | undefined): LucideGlyph | null {
  if (!looksLikeLucideIcon(value)) return null
  const name = (value as string).slice(PROJECT_ICON_PREFIX.length)
  return GLYPHS[name] ?? GLYPHS['folder-kanban']
}

/** Human label for a curated name: "folder-kanban" → "Folder kanban". */
export function iconLabel(name: string): string {
  const bare = name.startsWith(PROJECT_ICON_PREFIX) ? name.slice(PROJECT_ICON_PREFIX.length) : name
  const words = bare.replace(/-/g, ' ')
  return words.charAt(0).toUpperCase() + words.slice(1)
}

/** Stable swatch for a project that has none stored (hash of the name). */
export function defaultColorFor(seed: string | null | undefined): string {
  if (!seed) return DEFAULT_PROJECT_COLOR
  let h = 0
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0
  return PROJECT_COLORS[h % PROJECT_COLORS.length].value
}

/** Case-insensitive search over the curated set (name + label words). */
export function searchProjectIcons(query: string): ReadonlyArray<{ group: string; icons: readonly string[] }> {
  const q = query.trim().toLowerCase()
  if (!q) return PROJECT_ICON_GROUPS
  return PROJECT_ICON_GROUPS.map((g) => ({
    group: g.group,
    icons: g.icons.filter((n) => n.includes(q) || iconLabel(n).toLowerCase().includes(q)),
  })).filter((g) => g.icons.length > 0)
}

/** A sanitised colour for rendering: the stored value when it is #RRGGBB, else the hashed default. */
export function tileColor(color: string | null | undefined, seed?: string | null): string {
  return color && HEX_COLOR_RE.test(color) ? color : defaultColorFor(seed)
}
