import {
  CallHandler,
  ExecutionContext,
  Injectable,
  NestInterceptor,
} from '@nestjs/common';
import { ClsService } from 'nestjs-cls';
import type { Response } from 'express';
import { Observable } from 'rxjs';

/**
 * Echoes the per-request correlation id (generated by ClsModule, app.module.ts)
 * back as the `X-Request-ID` response header so client errors can be linked to
 * server logs. No-ops for non-HTTP contexts (e.g. websocket).
 */
@Injectable()
export class RequestIdInterceptor implements NestInterceptor {
  constructor(private readonly cls: ClsService) {}

  intercept(context: ExecutionContext, next: CallHandler): Observable<unknown> {
    if (context.getType() === 'http') {
      const res = context.switchToHttp().getResponse<Response>();
      const id = this.cls.getId();
      if (id && res && typeof res.setHeader === 'function' && !res.headersSent) {
        res.setHeader('X-Request-ID', id);
      }
    }
    return next.handle();
  }
}
