import { Injectable } from '@nestjs/common';
import { createElement as h } from 'react';
import {
  renderToBuffer,
  Document,
  Page,
  View,
  Text,
  StyleSheet,
} from '@react-pdf/renderer';

/**
 * Shape produced by PublicInvoiceService.assemble (getByToken / getById). Kept
 * loose (strings/nulls as stored) — the renderer coerces/formats.
 */
export interface InvoicePdfData {
  invoice: Record<string, unknown> & {
    invoice_number: string;
    status: string;
    invoice_date: string;
    due_date: string;
    currency: string;
  };
  line_items: Array<Record<string, unknown>>;
  customer: Record<string, unknown> | null;
  seller: Record<string, unknown> | null;
  payment_options?: { bank_transfer?: Record<string, unknown> | null } | null;
  show_powered_by?: boolean;
}

const s = (v: unknown): string => (v === null || v === undefined ? '' : String(v));
const num = (v: unknown): number => {
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
};

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 9, color: '#1f2937', fontFamily: 'Helvetica' },
  row: { flexDirection: 'row' },
  spread: { flexDirection: 'row', justifyContent: 'space-between' },
  sellerName: { fontSize: 15, fontFamily: 'Helvetica-Bold', color: '#111827' },
  title: { fontSize: 20, fontFamily: 'Helvetica-Bold', color: '#111827' },
  muted: { color: '#6b7280' },
  small: { fontSize: 8, color: '#6b7280' },
  sectionLabel: { fontSize: 8, color: '#6b7280', marginBottom: 3, textTransform: 'uppercase' },
  strong: { fontFamily: 'Helvetica-Bold' },
  block: { marginTop: 16 },
  // table
  th: {
    flexDirection: 'row',
    backgroundColor: '#f3f4f6',
    paddingVertical: 5,
    paddingHorizontal: 6,
    fontFamily: 'Helvetica-Bold',
    fontSize: 8,
  },
  td: {
    flexDirection: 'row',
    paddingVertical: 5,
    paddingHorizontal: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: '#e5e7eb',
  },
  totalsBox: { width: 230, marginTop: 12, marginLeft: 'auto' },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 2 },
  grandRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 5,
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: '#111827',
  },
  hr: { borderBottomWidth: 0.5, borderBottomColor: '#e5e7eb', marginVertical: 10 },
  footer: { position: 'absolute', bottom: 24, left: 36, right: 36, textAlign: 'center' },
});

// Column widths (flex) — GST columns are dropped for non-INR invoices.
const COLS_INR = { item: 3.2, hsn: 1, qty: 0.9, rate: 1.3, gst: 0.9, taxable: 1.3, total: 1.4 };
const COLS_FX = { item: 4, qty: 1, rate: 1.6, taxable: 1.7, total: 1.7 };

@Injectable()
export class InvoicePdfService {
  async render(data: InvoicePdfData): Promise<Buffer> {
    return renderToBuffer(this.document(data) as never) as unknown as Promise<Buffer>;
  }

  /** A stable file name for the Content-Disposition header. */
  fileName(data: InvoicePdfData): string {
    const n = s(data.invoice.invoice_number).replace(/[^A-Za-z0-9._-]/g, '_') || 'invoice';
    return `${n}.pdf`;
  }

  private document(data: InvoicePdfData) {
    const { invoice, line_items, customer, seller } = data;
    const currency = s(invoice.currency) || 'INR';
    const isInr = currency === 'INR';
    const money = (v: unknown) =>
      new Intl.NumberFormat(isInr ? 'en-IN' : 'en-US', {
        style: 'currency',
        currency,
        minimumFractionDigits: 2,
      }).format(num(v));

    return h(
      Document,
      { title: `Invoice ${s(invoice.invoice_number)}` },
      h(
        Page,
        { size: 'A4', style: styles.page },
        this.header(seller, invoice, money),
        h(View, { style: styles.hr }),
        this.parties(seller, customer, invoice),
        this.table(line_items, isInr, money),
        this.totals(invoice, isInr, money),
        this.bank(data.payment_options?.bank_transfer ?? null),
        this.notes(invoice),
        data.show_powered_by === false
          ? null
          : h(
              Text,
              { style: styles.footer, fixed: true },
              'Generated by Flicks Suite',
            ),
      ),
    );
  }

  private header(
    seller: Record<string, unknown> | null,
    invoice: Record<string, unknown>,
    money: (v: unknown) => string,
  ) {
    const docType = s(invoice.document_type) === 'QUOTE' ? 'QUOTE' : 'INVOICE';
    return h(
      View,
      { style: styles.spread },
      h(
        View,
        null,
        h(Text, { style: styles.sellerName }, s(seller?.legal_name) || s(seller?.name) || 'Company'),
        seller?.address_line1 ? h(Text, { style: styles.muted }, s(seller.address_line1)) : null,
        seller?.address_line2 ? h(Text, { style: styles.muted }, s(seller.address_line2)) : null,
        h(
          Text,
          { style: styles.muted },
          [s(seller?.city), s(seller?.state_code), s(seller?.postal_code)].filter(Boolean).join(', '),
        ),
        seller?.gstin ? h(Text, { style: styles.small }, `GSTIN: ${s(seller.gstin)}`) : null,
      ),
      h(
        View,
        { style: { textAlign: 'right' } },
        h(Text, { style: styles.title }, docType),
        h(Text, { style: styles.strong }, `# ${s(invoice.invoice_number)}`),
        h(Text, { style: styles.small }, `Date: ${s(invoice.invoice_date)}`),
        h(Text, { style: styles.small }, `Due: ${s(invoice.due_date)}`),
        h(Text, { style: { ...styles.small, marginTop: 2 } }, `Status: ${s(invoice.status)}`),
        h(Text, { style: { ...styles.strong, marginTop: 6, fontSize: 11 } }, money(invoice.total_amount)),
      ),
    );
  }

  private parties(
    seller: Record<string, unknown> | null,
    customer: Record<string, unknown> | null,
    invoice: Record<string, unknown>,
  ) {
    void seller;
    const addr = [
      s(customer?.billing_address_line1),
      s(customer?.billing_address_line2),
      [s(customer?.billing_city), s(customer?.billing_state), s(customer?.billing_postal_code)]
        .filter(Boolean)
        .join(', '),
      s(customer?.billing_country),
    ].filter(Boolean);
    return h(
      View,
      { style: styles.spread },
      h(
        View,
        { style: { width: '60%' } },
        h(Text, { style: styles.sectionLabel }, 'Bill To'),
        h(Text, { style: styles.strong }, s(customer?.legal_name) || s(customer?.display_name) || '—'),
        ...addr.map((l, i) => h(Text, { key: `a${i}`, style: styles.muted }, l)),
        customer?.gstin ? h(Text, { style: styles.small }, `GSTIN: ${s(customer.gstin)}`) : null,
      ),
      h(
        View,
        { style: { width: '35%' } },
        invoice.reference
          ? h(
              View,
              { style: { marginBottom: 4 } },
              h(Text, { style: styles.sectionLabel }, 'Reference'),
              h(Text, null, s(invoice.reference)),
            )
          : null,
        invoice.place_of_supply
          ? h(
              View,
              null,
              h(Text, { style: styles.sectionLabel }, 'Place of Supply'),
              h(Text, null, s(invoice.place_of_supply)),
            )
          : null,
      ),
    );
  }

  private table(
    items: Array<Record<string, unknown>>,
    isInr: boolean,
    money: (v: unknown) => string,
  ) {
    const cell = (text: string, flex: number, align: 'left' | 'right' = 'left', bold = false) =>
      h(
        Text,
        { style: { flex, textAlign: align, fontFamily: bold ? 'Helvetica-Bold' : 'Helvetica' } },
        text,
      );

    const head = isInr
      ? h(
          View,
          { style: styles.th },
          cell('Item', COLS_INR.item),
          cell('HSN/SAC', COLS_INR.hsn),
          cell('Qty', COLS_INR.qty, 'right'),
          cell('Rate', COLS_INR.rate, 'right'),
          cell('GST%', COLS_INR.gst, 'right'),
          cell('Taxable', COLS_INR.taxable, 'right'),
          cell('Amount', COLS_INR.total, 'right'),
        )
      : h(
          View,
          { style: styles.th },
          cell('Item', COLS_FX.item),
          cell('Qty', COLS_FX.qty, 'right'),
          cell('Rate', COLS_FX.rate, 'right'),
          cell('Taxable', COLS_FX.taxable, 'right'),
          cell('Amount', COLS_FX.total, 'right'),
        );

    const rows = items.map((it, idx) => {
      const total = it.line_total ?? it.line_amount ?? it.taxable_amount;
      return isInr
        ? h(
            View,
            { style: styles.td, key: `r${idx}`, wrap: false },
            h(
              View,
              { style: { flex: COLS_INR.item } },
              h(Text, null, s(it.item_name)),
              it.description ? h(Text, { style: styles.small }, s(it.description)) : null,
            ),
            cell(s(it.hsn_sac_code) || '—', COLS_INR.hsn),
            cell(s(it.quantity) + (it.unit ? ` ${s(it.unit)}` : ''), COLS_INR.qty, 'right'),
            cell(money(it.rate), COLS_INR.rate, 'right'),
            cell(`${num(it.gst_rate)}%`, COLS_INR.gst, 'right'),
            cell(money(it.taxable_amount), COLS_INR.taxable, 'right'),
            cell(money(total), COLS_INR.total, 'right'),
          )
        : h(
            View,
            { style: styles.td, key: `r${idx}`, wrap: false },
            h(
              View,
              { style: { flex: COLS_FX.item } },
              h(Text, null, s(it.item_name)),
              it.description ? h(Text, { style: styles.small }, s(it.description)) : null,
            ),
            cell(s(it.quantity) + (it.unit ? ` ${s(it.unit)}` : ''), COLS_FX.qty, 'right'),
            cell(money(it.rate), COLS_FX.rate, 'right'),
            cell(money(it.taxable_amount), COLS_FX.taxable, 'right'),
            cell(money(total), COLS_FX.total, 'right'),
          );
    });

    return h(View, { style: styles.block }, head, ...rows);
  }

  private totals(
    invoice: Record<string, unknown>,
    isInr: boolean,
    money: (v: unknown) => string,
  ) {
    const line = (label: string, value: unknown, opts: { grand?: boolean } = {}) =>
      h(
        View,
        { style: opts.grand ? styles.grandRow : styles.totalRow },
        h(Text, { style: opts.grand ? styles.strong : styles.muted }, label),
        h(Text, { style: opts.grand ? styles.strong : undefined }, money(value)),
      );

    const rows: ReturnType<typeof h>[] = [line('Subtotal', invoice.subtotal)];
    if (num(invoice.discount_amount) > 0) rows.push(line('Discount', -num(invoice.discount_amount)));
    rows.push(line('Taxable', invoice.taxable_amount));
    if (isInr) {
      if (num(invoice.cgst_amount) > 0) rows.push(line('CGST', invoice.cgst_amount));
      if (num(invoice.sgst_amount) > 0) rows.push(line('SGST', invoice.sgst_amount));
      if (num(invoice.igst_amount) > 0) rows.push(line('IGST', invoice.igst_amount));
      if (num(invoice.cess_amount) > 0) rows.push(line('Cess', invoice.cess_amount));
    }
    rows.push(line('Total', invoice.total_amount, { grand: true }));
    if (num(invoice.tds_amount) > 0) {
      rows.push(line(`TDS${invoice.tds_rate ? ` (${num(invoice.tds_rate)}%)` : ''}`, -num(invoice.tds_amount)));
      rows.push(line('Net Receivable', invoice.net_receivable ?? invoice.total_amount));
    }
    if (num(invoice.amount_paid) > 0) {
      rows.push(line('Paid', -num(invoice.amount_paid)));
      rows.push(line('Balance Due', invoice.amount_outstanding, { grand: true }));
    }
    return h(View, { style: styles.totalsBox }, ...rows);
  }

  private bank(bank: Record<string, unknown> | null) {
    if (!bank) return null;
    const field = (label: string, value: unknown) =>
      value
        ? h(Text, { style: styles.muted }, `${label}: ${s(value)}`)
        : null;
    return h(
      View,
      { style: styles.block },
      h(Text, { style: styles.sectionLabel }, 'Bank Transfer'),
      field('Beneficiary', bank.beneficiary_name),
      field('Account No', bank.account_number),
      field('Bank', bank.bank_name),
      field('Branch', bank.branch),
      field('IFSC', bank.ifsc),
      field('SWIFT/BIC', bank.swift_bic),
    );
  }

  private notes(invoice: Record<string, unknown>) {
    if (!invoice.notes && !invoice.terms_and_conditions) return null;
    return h(
      View,
      { style: styles.block },
      invoice.notes
        ? h(
            View,
            { style: { marginBottom: 6 } },
            h(Text, { style: styles.sectionLabel }, 'Notes'),
            h(Text, { style: styles.muted }, s(invoice.notes)),
          )
        : null,
      invoice.terms_and_conditions
        ? h(
            View,
            null,
            h(Text, { style: styles.sectionLabel }, 'Terms & Conditions'),
            h(Text, { style: styles.muted }, s(invoice.terms_and_conditions)),
          )
        : null,
    );
  }
}
