-- One-off cleanup so you can re-test the timesheet flow end-to-end.
-- Resets any submitted/approved/rejected timesheets for Alice (and Diya, who
-- got the rework notification by mistake during prior testing) back to
-- draft, clears review state, and deletes any in-app notifications
-- generated by the earlier round. Safe to re-run — no-op if rows are
-- already in the target state.
--
-- Apply via the Supabase SQL editor or:
--   psql "$DATABASE_DIRECT_URL" -f scripts/reset-timesheet-demo.sql

BEGIN;

WITH demo_users AS (
  SELECT id FROM users
  WHERE email IN ('alice@demo.co', 'diya@demo.co')
),
demo_employees AS (
  SELECT e.id
  FROM employees e
  WHERE e.user_id IN (SELECT id FROM demo_users)
)
UPDATE timesheet_periods
SET    status            = 'draft',
       submitted_at      = NULL,
       approved_at       = NULL,
       rejected_at       = NULL,
       rejection_comment = NULL,
       updated_at        = now()
WHERE  employee_id IN (SELECT id FROM demo_employees)
  AND  status <> 'draft';

-- Drop any rework requests from those resets.
DELETE FROM timesheet_rework_requests
WHERE  timesheet_period_id IN (
  SELECT tp.id
  FROM   timesheet_periods tp
  JOIN   employees e ON e.id = tp.employee_id
  JOIN   users u ON u.id = e.user_id
  WHERE  u.email IN ('alice@demo.co', 'diya@demo.co')
);

-- Clear notifications for Alice + Diya so the bell starts empty.
DELETE FROM notifications
WHERE  user_id IN (
  SELECT id FROM users
  WHERE  email IN ('alice@demo.co', 'diya@demo.co')
);

COMMIT;

-- Spot-check:
--   select tp.id, u.email, tp.status, tp.period_start, tp.submitted_at
--   from timesheet_periods tp
--   join employees e on e.id = tp.employee_id
--   join users u on u.id = e.user_id
--   where u.email in ('alice@demo.co','diya@demo.co');
